/******************************************************************************
 *  Name:              Ryan Ben S. Villanueva
 *  1.2.27 Gaussian random numbers. Write a program RandomGaussian
 *  that prints a random number r drawn from the Gaussian distribution. One way
 *  to do so is to use the Box–Muller formula r = sin(2*pi*v) (-2 ln u)^1/2
 *  where u and v are real numbers between 0 and 1 generated by the
 *  Math.random() method.
 *  Last modified:     October 13, 2019
 **************************************************************************** */

public class RandomGaussian {
    public static void main(String[] args) {
        double u = Math.random();
        double v = Math.random();

        double r = Math.sin(2 * Math.PI * v) * Math.sqrt(-2 * Math.log(u));
        System.out.println(r);
    }
}
